### ISSUE TITLE
nothing happens when I run this...?

### ISSUE THREAD

**Issue by pnunn** [homer6/frequent-cron#10]
Hi, 
I've compiled frequent-cron and it seems to be running (it shows up in ps -A happily), but, it doesn't seem to do anything.

I've got a simple script that just has 
/usr/bin/echo `data` >> /home/usr/out.txt 
in it.. and I try and start frequent-cron with 
./frequent-cron --frequency=100 --command="/usr/bin/bash /home/usr/echoout.sh"

but absolutely nothing happens.

What am I missing?

**Comment by homer6** [comment]
My apologies for not noticing this issue earlier.

frequent-cron runs as a daemon, so it fork/execs from the shell. It's running in the background. See: https://github.com/homer6/frequent-cron/blob/master/src/frequent.cc#L106
