### ISSUE TITLE
Question: run as cron at minutes interval

### ISSUE THREAD

**Issue by whitetiger21022014** [homer6/frequent-cron#4]
Dear Homer6,
Do you know how can i run your daemon as scheduling job?
Example:
Run every 5 minutes: at 0,5,15,20,....55 minutes
Run every 2 minutes: at 0,2,4....58

**Comment by homer6** [comment]
Hello,

If that's your use case, you could certainly use `frequent-cron` for that. However, I'd recommend just using `crontab` or https://kubernetes.io/docs/user-guide/cron-jobs/

Frequent-cron primarily helps for sub-minute types of events that need to block. For example, running a worker that listens to a blocking queue such as https://redis.io/commands/blpop or Kafka. The worker is ephemeral and thus gets restarted when it completes or the blocking times out. However, the events can be processed asynchronously without worry of the worker crashing or running for too long.

Frequent-cron is lightweight enough that it doesn't have concerns for memory defragmentation or other resource exhaustion and thus is stable for invoking workers described above.

Please let me know how you make out.

Thanks,

Steve

**Comment by whitetiger21022014** [comment]
I will do as your reply. Thanks you so much
