### ISSUE TITLE
Any way to run frequent-cron non-blocking?

### ISSUE THREAD

**Issue by Kramerican** [homer6/frequent-cron#5]
I have always seen the default behavior of frequent-cron as a strength as it has been what I needed in past projects.

However, I have a scenario now where I basically want a script to be run every 500ms regardless of whether there is a copy of the script running already.

Is there a way to tell frequent cron to be non-blocking and just run the requested command ever Xms regardless?

Maybe some other daemon you know of which does this, in case this is not do-able with frequent-cron?

Thanks! :)

**Comment by Kramerican** [comment]
Nevermind - this is easily achievable by just adding an ampersand to whatever commands you want to run in parallel (non-blocking) in your script, at least in Bash. 

`foo args &`

**Comment by homer6** [comment]
Hi @Kramerican,

Unfortunately, adding a non-blocking mode add a few complications, in terms of stability. Are you able to explain a little more of what you're trying to accomplish and why?

It may still be the way to go, but it'll help me understand your approach and potentially suggest an alternative.

Thanks

**Comment by Kramerican** [comment]
Hello

Well essentially I'm using frequent-cron to launch a script which watches a directory for files containing commands that need to be executed. Obviously we then ran into the issue that some commands would take a long time to complete, which meant a queue would form where users were waiting for some other user's long-running command to complete.

Frequent-cron was our choice as we needed the commands to be picked up and executed as quickly as possible. There was no need for serial execution.

The ampersand solved the "issue" as that allowed us to execute all commands in parallel, mark the the files as processed and then exit the script - then the next instance of frequent-cron would run and repeat the process. All is well :)

Thank you for responding!

**Comment by Kramerican** [comment]
PS: The only "bad" side-effect we have noticed is that, as we pipe our command output to log files, this asynchronous processing can result in dis-jointed logs. I.e. you have log lines of one long-running command beginning, and then you have log lines from other commands which were executed in the midst of things. But that's a small price to pay for a better user experience.

**Comment by homer6** [comment]
To be honest, I'd suggest using kubernetes for each worker and dumping the messages into http://nsq.io/

Using the filesystem can be a bit error-prone (even with flock). And, you'll run into issues with scaling, HA, and fault tolerance.

For what they're worth, my 2 cents...

**Comment by homer6** [comment]
@Kramerican How did you make out with this?

**Comment by homer6** [comment]
I just created a new branch: "feature/asynchronous" that has this feature. I've run into strange issues with the ampersand trick in the past. Please let me know if this works for you.

Cheers,

Steve

**Comment by Kramerican** [comment]
@homer6 Thanks! I reviewed the source and I see you are forking. Could you elaborate why that is better than the ampersand trick?

In any case, you are in luck: I have a dedicated test system these days in order to test Bionic upgrading, so I will give this a spin. It might not be untill after the weekend though, as tomorrow is a national holiday here. I'll report back here once I've tried it out.

**Comment by homer6** [comment]
I've noticed that, if the command that you're calling _also calls system()_, some of the commands that are called in that second `system()` call may not receive the arguments properly. The failure would depend on that last process is reading arguments. In the case that I described, removing the ampersand trick resolved the issue. It's an edge case, but something I've avoided since.
