### ISSUE TITLE
After Ubuntu 18.04 upgrade, libboost cannot be found and frequent cron must be rebuilt

### ISSUE THREAD

**Issue by Kramerican** [homer6/frequent-cron#7]
This is not a bug report per say, but something which might help others.

After upgrading from 16.04 LTS to 18.04 LTS today I had to rebuild frequent-cron as I got this message when attempting to start the daemon:

`/root/frequent-cron/frequent-cron: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory`

I basically just had to re-run the make process:

`cd /root/frequent-cron; cmake .; make;`

And frequent-cron is happy again :+1:

**Comment by homer6** [comment]
Thanks @Kramerican!
